name: Build Launcher
on:
  workflow_dispatch: { }
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Patch Submodules
        run: powershell -ExecutionPolicy Bypass -File .\patch-submodules.ps1
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-binstall and flutter_rust_bridge_codegen
        run: |
          Invoke-WebRequest https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-pc-windows-msvc.zip -OutFile binstall.zip
          Expand-Archive binstall.zip -DestinationPath . -Force
          ./cargo-binstall.exe -y --force flutter_rust_bridge_codegen@2.11.1
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - uses: arduino/setup-protoc@v3
      - name: Bootstrap
        run: |
          dart pub global activate melos
          dart pub global run melos bootstrap
      - name: Build Rust Library
        working-directory: ./Launcher/rust
        run: cargo build --release
      - name: Build Launcher
        working-directory: ./Launcher
        run: |
          dart run tool/ffigen.dart
          flutter build windows
      - name: Bundle Maxima and Rust Library
        run: |
          Invoke-WebRequest https://s3.kyber.gg/artifacts/maxima-win64.zip -OutFile maxima.zip
          Expand-Archive maxima.zip -DestinationPath maxima_files -Force
          copy maxima_files/maxima-service.exe Launcher/build/windows/x64/runner/Release/maxima-service.exe
          copy maxima_files/maxima-bootstrap.exe Launcher/build/windows/x64/runner/Release/maxima-bootstrap.exe
          copy Launcher/rust/target/release/rust_lib.dll Launcher/build/windows/x64/runner/Release/rust_lib.dll
      - uses: actions/upload-artifact@v4
        with:
          name: kyber-launcher
          path: Launcher/build/windows/x64/runner/Release/
