name: Build API
on:
  workflow_dispatch: { }
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - uses: arduino/setup-protoc@v3
      - name: Build
        working-directory: ./API
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          .\scripts\gen-proto.bat
          go build -o kyber-api.exe ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: kyber-api
          path: API/kyber-api.exe
