name: Build Proxy
on:
  workflow_dispatch: { }
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
      - uses: arduino/setup-protoc@v3
      - name: Build
        working-directory: ./Proxy
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: kyber-proxy
          path: Proxy/target/release/kyber_proxy.exe
