name: Build Launcher
on:
  workflow_dispatch: { }
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Patch Submodules
        run: powershell -ExecutionPolicy Bypass -File .\patch-submodules.ps1
      - uses: dtolnay/rust-toolchain@nightly
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - uses: arduino/setup-protoc@v3
      - name: Bootstrap
        run: |
          dart pub global activate melos
          dart pub global run melos bootstrap
      - name: Build
        working-directory: ./Launcher
        run: |
          dart run tool/ffigen.dart
          flutter build windows
      - uses: actions/upload-artifact@v4
        with:
          name: kyber-launcher
          path: Launcher/build/windows/x64/runner/Release/
