name: Build Module
on:
  workflow_dispatch: { }
  push:
    paths: [ 'Module/**/*', '.github/workflows/build-module.yaml' ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: gcc
          location: C:\msys64
      - name: Build
        run: |
          Invoke-WebRequest https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-windows-amd64.exe -OutFile C:\Windows\bazel.exe
          mkdir C:\bz
          bazel --output_user_root="C:\bz" build --config=release Kyber
      - uses: actions/upload-artifact@v4
        with:
          name: kyber-module
          path: bazel-bin/Kyber.dll
