name: Build Launcher
on:
  workflow_dispatch: { }
  push:
    paths: [ 'Launcher/**/*', '.github/workflows/build-launcher.yml' ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - uses: arduino/setup-protoc@v3
      - name: Build
        working-directory: ./Launcher
        run: |
          dart run tool/ffigen.dart
          flutter build windows
      - uses: actions/upload-artifact@v4
        with:
          name: kyber-launcher
          path: Launcher/build/windows/x64/runner/Release/
